### ISSUE TITLE
По правилам БЭМ не стоит обращаться к элементу по селектору его тэга

### ISSUE THREAD

**Issue by ShukshinaMI** [baffanton/diploma#2]
[https://github.com/baffanton/diploma/blob/main/src/modules/Header/style.scss](url)
```
.header__company **svg** {     
      height: 60px; 
}
```

**Comment by ShukshinaMI** [comment]
```
**svg**.icon_disabled {
    cursor: default;
    color: $grey;
}
```

**Comment by ShukshinaMI** [comment]
Такое тоже не приветствуется БЭМ, лучше задать font-family всей странице, это свойство наследуется, а вот box-sizing не наследуется - посмотри как лучше поступить
```
* {
    font-weight: 400;
    font-size: 1.25rem;
    font-family: 'Roboto';
    margin-block-start: 0;
    margin-block-end: 0;
    box-sizing: border-box;
    position: relative;
}
```

**Comment by baffanton** [comment]
С SVG разобрался, а вот что делать с box-sizing не совсем. Можно было бы передать его просто в Layout, но он нужен не только там
