### ISSUE TITLE
Разве header это модуль?

### ISSUE THREAD

**Issue by ShukshinaMI** [baffanton/diploma#3]
![image](https://github.com/baffanton/diploma/assets/74698961/5d56cf53-cfe3-41b8-ba16-c871459617f9)

**Comment by baffanton** [comment]
Если честно, то я не особо понимаю как их раскидать. Header - вообще уникальный компонент, который можно в widgets закинуть

**Comment by ShukshinaMI** [comment]
#7 вот тут почитай
